_wandb:
    value:
        cli_version: 0.22.3
        e:
            4jotc9gu7ga4tn8uq43ukw6artjynb0q:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 24
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "20401094656"
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "1995218165760"
                        used: "469787885568"
                email: chris.wendler@epfl.ch
                executable: /Users/chriswendler/Documents/2025/code/toy-wm/.venv/bin/python3
                git:
                    commit: bc6412e761d7a54e8d9f2472fcfd0bbb1481e603
                    remote: git@github.com:wendlerc/toy-wm.git
                host: Chriss-MacBook-Air.local
                memory:
                    total: "25769803776"
                os: macOS-15.6-arm64-arm-64bit-Mach-O
                program: -m src.main
                python: CPython 3.13.5
                root: /Users/chriswendler/Documents/2025/code/toy-wm
                startedAt: "2025-11-02T05:20:06.601387Z"
                writerId: 4jotc9gu7ga4tn8uq43ukw6artjynb0q
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
            "4": 3.13.5
            "5": 0.22.3
            "12": 0.22.3
            "13": darwin-arm64
