model:
  model_id: "dit_dforce"
  width: 24
  height: 24
  T: 1000
  in_channels: 3
  n_window: 30
  patch_size: 3
  n_heads: 12
  d_model: 384
  n_blocks: 8
  C: 5000
  bidirectional: true
  nocompile: false
  checkpoint: "experiments/summer-thunder-631/model.pt"
  rope_type: "vid"

train:
  lr1: 0.02
  lr2: 3.0e-4
  betas: [0.9, 0.95]
  weight_decay: 1.0e-5
  max_steps: 10000
  warmup_steps: 100
  batch_size: 20
  noclip: false
  duration: 1
  fps: 30
  debug: false
  dtype: "bf16"
  

wandb:
  name: null
  project: "toy-wm"
  run_name: "bidirectional-layers8-heads12-d384"
