model:
  model_id: "dit_dforce"
  width: 24
  height: 24
  T: 1000
  in_channels: 3
  n_window: 30
  patch_size: 3
  n_heads: 12
  d_model: 384
  n_blocks: 8
  C: 5000
  bidirectional: false
  nocompile: false
  checkpoint: "experiments/frosty-sunset-395/ckpt-step=002100-metric=0.00160125.pt"
  #checkpoint: "experiments/vivid-sea-390/ckpt-step=000700-metric=0.01958773.pt"

train:
  lr1: 0.02
  lr2: 3.0e-5
  betas: [0.9, 0.95]
  weight_decay: 1.0e-5
  max_steps: 160000
  batch_size: 16
  noclip: false
  duration: 1
  fps: 30
  debug: false

wandb:
  name: null
  project: "toy-wm"
  run_name: "causal-layers8-heads12-d384"
