model:
  model_id: "dit_dforce"
  width: 24
  height: 24
  T: 1000
  in_channels: 3
  n_window: 30
  patch_size: 4
  n_heads: 4
  d_model: 64
  n_blocks: 12
  bidirectional: false
  nocompile: false
  checkpoint: "experiments/olive-glade-151/model.pt"

train:
  lr1: 0.002
  lr2: 3.0e-5
  betas: [0.9, 0.95]
  weight_decay: 1.0e-5
  max_steps: 200000
  batch_size: 32
  noclip: false
  duration: 1
  fps: 30
  in_channels: 3
  debug: false

wandb:
  name: null
  project: "toy-wm"
  run_name: null
