model:
  model_id: null
  width: 24
  height: 24
  T: 1000
  in_channels: 3
  n_window: 7
  patch_size: 1
  n_heads: 12
  d_model: 384
  n_blocks: 12
  bidirectional: true
  nocompile: false
  checkpoint: null

train:
  lr1: 0.002
  lr2: 3.0e-5
  betas: [0.9, 0.95]
  weight_decay: 1.0e-5
  max_steps: 26000
  batch_size: 32
  noclip: false
  duration: 1
  fps: 7
  in_channels: 3
  debug: false

wandb:
  name: "toy-wm"
  project: null
  run_name: null
