model:
  model_id: "dit_dforce"
  width: 24
  height: 24
  T: 1000
  in_channels: 3
  n_window: 30
  patch_size: 3
  n_heads: 6
  d_model: 396
  n_blocks: 8
  C: 5000
  bidirectional: false
  nocompile: false
  checkpoint: "experiments/glowing-violet-635/ckpt-step=031500-metric=0.00135337.pt" 
  #"experiments/absurd-oath-640/ckpt-step=012600-metric=0.00166822.pt"
  rope_type: "vid"
  #"experiments/worldly-water-607/ckpt-step=005900-metric=0.00670522.pt"
  #"experiments/comic-silence-613/model.pt"
  #checkpoint: "experiments/playful-field-611/model.pt"
  #"experiments/bigger_30frame_causal/pytorch_model.pt"
  #"experiments/playful-field-611/model.pt"
  #"experiments/playful-field-611/ckpt-step=001600-metric=0.00165918.pt"
  #"experiments/bigger_30frame_causal/pytorch_model.pt"
  #"experiments/pleasant-plasma-596/model.pt"
  #"experiments/pleasant-plasma-596/model.pt"
  #"experiments/fancy-yogurt-597/ckpt-step=005700-metric=0.00129715.pt"
  #"experiments/graceful-lake-595/ckpt-step=002600-metric=0.01305500.pt"
  #"experiments/pleasant-plasma-596/ckpt-step=038800-metric=0.00026014.pt"
  #"experiments/devout-microwave-587/model.pt"
  #"experiments/graceful-lake-595/ckpt-step=001700-metric=0.01513267.pt"
  #"experiments/devout-microwave-587/ckpt-step=013400-metric=0.00126181.pt"
  #"experiments/bigger_30frame_causal/pytorch_model.pt"
  #"experiments/devout-microwave-587/ckpt-step=008800-metric=0.00166038.pt"
  #"experiments/fancy-sea-584/ckpt-step=003200-metric=0.00033609.pt"
  #"experiments/bigger_30frame_causal/pytorch_model.pt"

train:
  lr1: 0.02
  lr2: 3.0e-5
  betas: [0.9, 0.95]
  weight_decay: 1.0e-5
  max_steps: 5000
  batch_size: 256
  noclip: false
  duration: 1
  fps: 1
  debug: 
  warmup_steps: 100

wandb:
  name: null
  project: "toy-wm"
  run_name: "causal-layers8-heads12-d384"