model:
  model_id: "dit_dforce"
  width: 24
  height: 24
  T: 1000
  in_channels: 3
  n_window: 30
  patch_size: 3
  n_heads: 12
  d_model: 384
  n_blocks: 8
  C: 5000
  bidirectional: false
  nocompile: false
  checkpoint: "experiments/bigger_30frame_causal/pytorch_model.pt"

train:
  lr1: 0.02
  lr2: 3.0e-5
  betas: [0.9, 0.95]
  weight_decay: 1.0e-5
  max_steps: 5000
  batch_size: 256
  noclip: false
  duration: 1
  fps: 1
  debug: false

wandb:
  name: null
  project: "toy-wm"
  run_name: "causal-layers8-heads12-d384"