model:
  model_id: "dit_dforce"
  width: 24
  height: 24
  T: 1000
  in_channels: 3
  n_window: 30
  patch_size: 3
  n_heads: 12
  d_model: 384
  n_blocks: 8
  C: 5000
  bidirectional: false
  nocompile: false
  #checkpoint: "experiments/azure-glitter-510/ckpt-step=000100-metric=0.00780431.pt"
  checkpoint: "experiments/radiant-forest-398/ckpt-step=053700-metric=0.00092727.pt"
  # few frame 2-step distilled model experiments/smart-waterfall-528/model.pt
  #"experiments/rich-meadow-488/model.pt"
  # "experiments/rich-meadow-488/ckpt-step=003700-metric=0.00309512.pt"
  #checkpoint: "experiments/radiant-forest-398/ckpt-step=053700-metric=0.00092727.pt"
  #checkpoint: "experiments/glad-water-486/model.pt"
  #checkpoint: "experiments/dutiful-river-427/ckpt-step=011600-metric=0.00229805.pt"
  #checkpoint: "experiments/iconic-paper-421/ckpt-step=001600-metric=0.00471355.pt"
  #"experiments/radiant-forest-398/ckpt-step=053700-metric=0.00092727.pt"
  #checkpoint: "experiments/frosty-sunset-395/ckpt-step=002100-metric=0.00160125.pt"
  #checkpoint: "experiments/vivid-sea-390/ckpt-step=000700-metric=0.01958773.pt"

train:
  lr1: 0.0002
  lr2: 1.5e-6
  betas: [0.9, 0.95]
  weight_decay: 1.0e-5
  max_steps: 20000
  batch_size: 16
  noclip: false
  duration: 1
  fps: 31
  debug: false
  p_pretrain: 0.95

wandb:
  name: null
  project: "toy-wm"
  run_name: "causal-layers8-heads12-d384"
