model:
  model_id: "dit_dforce"
  width: 24
  height: 24
  T: 1000
  in_channels: 3
  n_window: 30
  patch_size: 4
  n_heads: 4
  d_model: 128
  n_blocks: 6
  bidirectional: false
  nocompile: false
  checkpoint: null

train:
  lr1: 0.02
  lr2: 3.0e-4
  betas: [0.9, 0.95]
  weight_decay: 1.0e-5
  max_steps: 100000
  batch_size: 64
  noclip: false
  duration: 1
  fps: 30
  debug: false

wandb:
  name: null
  project: "toy-wm"
  run_name: "causal-layers6-heads4-d128"
