model:
  model_id: "dit_dforce"
  width: 24
  height: 24
  T: 1000
  in_channels: 3
  n_window: 30
  patch_size: 4
  n_heads: 8
  d_model: 256
  n_blocks: 6
  bidirectional: true
  nocompile: false
  checkpoint: "experiments/glad-fire-362/ckpt-step=002600-metric=0.05778494.pt"

train:
  lr1: 0.002
  lr2: 3.0e-5
  betas: [0.9, 0.95]
  weight_decay: 1.0e-5
  max_steps: 100000
  batch_size: 32
  noclip: false
  duration: 1
  fps: 30
  debug: false

wandb:
  name: null
  project: "toy-wm"
  run_name: "bidir-layers6-heads8-d256"
