model:
  model_id: null
  width: 24
  height: 24
  T: 1000
  in_channels: 3
  n_window: 1
  patch_size: 2
  n_heads: 8
  d_model: 256
  n_blocks: 2
  bidirectional: true
  nocompile: true
  checkpoint: null

train:
  lr1: 0.002
  lr2: 3.0e-5
  betas: [0.9, 0.95]
  weight_decay: 1.0e-5
  max_steps: 5000
  batch_size: 256
  noclip: false
  duration: 1
  fps: 1
  in_channels: 3
  debug: true

wandb:
  name: null
  project: "toy-wm"
  run_name: null
