model:
  model_id: null
  width: 24
  height: 24
  T: 1000
  in_channels: 3
  n_window: 6
  patch_size: 4
  n_heads: 4
  d_model: 128
  n_blocks: 4
  bidirectional: true
  nocompile: true
  checkpoint: "experiments/genial-lion-347/ckpt-step=004900-metric=0.06114923.pt"

train:
  lr1: 0.02
  lr2: 3.0e-4
  betas: [0.9, 0.95]
  weight_decay: 1.0e-5
  max_steps: 5000
  batch_size: 32
  noclip: false
  duration: 1
  fps: 6
  in_channels: 3
  debug: false

wandb:
  name: null
  project: "toy-wm"
  run_name: null
